sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
  - '4'
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run report-coverage
  - npm run release
